export const UPDATE_MENU = 'UPDATE_MENU';
export const ADD_MENU = 'ADD_MENU';
export const SET_MENU = 'SET_MENU';
export const DELETE_MENU = 'DELETE_MENU';

export const SET_SKILLS = 'SET_SKILLS';

export const SET_USER_DATA = 'SET_USER_DATA';
export const IS_AUTH_USER = 'IS_AUTH_USER';

export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const SET_FEEDBACK_COUNT = 'SET_FEEDBACK_COUNT';

export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';

export const NEW_PORTFOLIO = 'NEW_PORTFOLIO';
export const SET_PORTFOLIO = 'SET_PORTFOLIO';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PORTFOLIO_SINGLE = 'SET_PORTFOLIO_SINGLE';
export const SET_PORTFOLIO_LIKE = 'SET_PORTFOLIO_LIKE';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';

export const SET_SERVICES = 'SET_SERVICES';
export const SET_SERVICE_SINGLE = 'SET_SERVICE_SINGLE';
export const UPDATE_SERVICE_SINGLE = 'UPDATE_SERVICE_SINGLE';
export const CLEAR_SERVICE_SINGLE = 'CLEAR_SERVICE_SINGLE';

export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS';